### ISSUE TITLE
Deploy to Bluemix: Could not find service everedis

### ISSUE THREAD

**Issue by cclauss** [ibmjstart/bluemix-python-eve-sample#5]
```
Done uploading
OK
FAILED
Could not find service everedis to bind to bluemix-python-eve-sample-cclauss

Finished: FAILED

Stage has no runtime information
```

**Comment by joshisa** [comment]
@cclauss I couldn't reproduce.  Not sure why the declared-service within the manifest.yml was not pre-created for you within your space.   Easy workaround is to create the service via CLI  (e.g.  `cf create-service rediscloud 30mb everedis` ).  Not sure if this could be side-effect from the manifest being incompatible with the deploy-to-bluemix backend when you tried last.  I recently accepted a PR for #4 .   If it's not too much trouble, please delete your project, deployed app and services and try the button again.

**Comment by cclauss** [comment]
I would still be very interested to see how this is done.

**Comment by joshisa** [comment]
@cclauss To better handle the everedis failure related to rediscloud limitations on number of free instances, the new merge which includes a custom devOps pipeline also adds a SetupServices job that attempts to create a redis service instance using the experimental redis service instance (if a service instance with that name is not found already).  Obviously, the experimental services are ok for playing around -- but I'd recommend MongoDB,Redis by Compose if you need anything close to reliable for your Eve API deployment.  Also revved up all of the dependencies to latest.  Give the button a try and see if the new custom pipeline helps alleviate the failure.  I'll await your comment and feedback before closing.  Thanks.

**Comment by cclauss** [comment]
@joshisa Thanks massively for this.  It works like a charm.

I will need to study your changes in `.bluemix/pipeline.yml` for a while before I understand exactly how it works.  It looks very promising.

The only minor issue I saw in the logs was about Python 2.7.11 vs. 2.7.9 but it is really a minor point:

```
STG/0    -----> Installing python-2.7.11

STG/0    Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/69221686-9e15-442c-bdec-fd0fb5fc5470_ca60152b78be3f93067cd4f03d01e2db810ac2a8/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_python_python-2.7.11-linux-x64.tgz]

[ ... ]

STG/92   -----> Uploading droplet (37M)

DEA/92   Starting app instance (index 0) with guid 5b2766e9-bead-4dc5-af10-cd5caf8d1893

App/0    Welcome to Bluemix

App/0    Running on Python Version: 2.7.9
```
