### ISSUE TITLE
flake8 to provide PEP8 code syntax testing

### ISSUE THREAD

**Issue by cclauss** [ibmjstart/bluemix-python-eve-sample#6]
README.md says [flake8 to provide PEP8 code syntax testing](https://github.com/ibmjstart/bluemix-python-eve-sample/edit/master/README.md#L52).

Could the flake8 test be a step in the build process such that if there are flake8 issues, the deployment is halted?

**Comment by joshisa** [comment]
@cclauss Great suggestion. Absolutely.  I actually did that for a project a while back.  I'd need to update the repo with a .bluemix folder that contains a pipeline.yml file that customizes the pipeline to include a flake8 download and execute test job.  T

**Comment by cclauss** [comment]
Awesome...  That would be really cool to see.  I have been hacking on https://github.com/cclauss/python3wos_asyncio on and off for a few weeks and it would be great if flake8 issues stopped the build process.

**Comment by joshisa** [comment]
@cclauss Just merged some changes into master to illustrate support for custom devOps pipelines and unit testing.  Also revved up all of the dependencies to latest.  Added a new testing section in the readme.  2 re-usable bash scripts are the core of the unit test jobs in the pipeline.  They download and setup things to run flake8 and a test infra to support nosetests.  They'll kill the pipeline if they fail.  They are now automatically used by the custom pipeline defined in a yaml file.  Check it out and let me know if this meets your needs.  I'll then close the issue.

**Comment by joshisa** [comment]
@cclauss Closing the issue.  I made a bunch of tweaks to the repo to flush out some remaining bugs with how the test logs behaved and how they generated XUnit formatted xml files.  Tested a few times and everything seems to behave as expected.  Please re-open or open new if you run into any weirdness with the custom pipeline test jobs.
- [x] [Custom Pipeline Example](https://github.com/ibmjstart/bluemix-python-eve-sample/blob/master/.bluemix/pipeline.yml)
- [x] [PEP8 Custom Pipeline Test Job Script](https://github.com/ibmjstart/bluemix-python-eve-sample/blob/master/macreduce/tests/pep8_style_tests.sh)
- [x] [Nose Custom Pipeline Test Job Script](https://github.com/ibmjstart/bluemix-python-eve-sample/blob/master/macreduce/tests/nose_unit_tests.sh)

**Comment by cclauss** [comment]
Agreed...  These are great additions.  Thanks.
